version: "3.7"

services:
  launch:
    # environment:
    #   - GIT_HASH=${GIT_HASH:-docker-from-docker}
    image: ypolosov/containered-demo:${GIT_HASH}
    container_name: containered-demo-${GIT_HASH}
    tty: true
    ports:
      - 4200:4200
    init: true
    volumes:
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.docker:/home/node/.docker
      - /var/run/docker.sock:/var/run/docker-host.sock
      # for Linux
      - .:/workspace:cached
      # for macOS
      # - .:/workspace:delegated
