version: "3.7"

services:
  launch:
    image: ypolosov/containered-demo:${TAG}
    container_name: containered-demo-${TAG}
    tty: true
    ports:
      - 4200:4200
    volumes:
      - .:/workspace:cached
     # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
