version: "3.7"

services:
  launch:
    # environment:
    #   - GIT_HASH=${GIT_HASH:-docker-from-docker}
    image: ypolosov/containered-demo:${GIT_HASH}
    container_name: containered-demo-${GIT_HASH}
    tty: true
    ports:
      - 4200:4200
    init: true
    volumes:
      - ~/.gitconfig:/home/node/.gitconfig:ro
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.docker:/home/node/.docker:ro
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/workspace:cached
     # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
