version: "3.7"

services:
  launch:
    image: ypolosov/containered-demo:${GIT_HASH}
    container_name: containered-demo-${GIT_HASH}
    tty: true
    ports:
      - 4200:4200
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
     # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
